# Generated by Django 5.1.6 on 2025-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamsettings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
