# Generated by Django 5.2 on 2025-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_emote_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="stream_id",
            field=models.CharField(
                default="general",
                help_text="Stream identifier for chat grouping",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["stream_id", "-timestamp"],
                name="home_chatme_stream__9d8fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "-timestamp"], name="home_chatme_user_id_1eb09d_idx"
            ),
        ),
    ]
