# Generated by Django 5.2 on 2026-02-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_streamsettings_updated_by'),
        ('home', '0004_auth_overhaul'),
    ]

    operations = [
    ]
