# Generated by Django 5.1.6 on 2025-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_streamsettings_unique_active_stream"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamsettings",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="streamsettings",
            name="unique_active_stream",
        ),
        migrations.AddField(
            model_name="streamsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="streamsettings",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="streamsettings",
            name="channel_slug",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="streamsettings",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
