# Generated by Django 5.1.6 on 2025-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_streamsettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamsettings",
            name="platform",
            field=models.CharField(
                choices=[
                    ("kick", "Kick"),
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                ],
                default="kick",
                max_length=10,
            ),
        ),
    ]
