# Generated by Django 5.1.6 on 2025-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_streamsettings_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamsettings",
            name="youtube_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Required for YouTube streams. Find in channel URL.",
                max_length=100,
                null=True,
            ),
        ),
    ]
