# Generated by Django 5.2 on 2026-02-17 00:14

from django.db import migrations


def set_admin_role_for_staff(apps, schema_editor):
    CustomUser = apps.get_model('home', 'CustomUser')
    CustomUser.objects.filter(is_staff=True).update(role='admin')


def reverse_admin_role(apps, schema_editor):
    CustomUser = apps.get_model('home', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_user_roles_and_moderation"),
    ]

    operations = [
        migrations.RunPython(set_admin_role_for_staff, reverse_admin_role),
    ]
