# Generated by Django 5.2 on 2026-03-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_set_admin_role_for_staff'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='home_invita_token_h_d2de43_idx',
            old_name='home_invita_token_h_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='home_invita_email_694200_idx',
            old_name='home_invita_email_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='home_passwo_token_h_c393ed_idx',
            old_name='home_passwo_token_h_idx',
        ),
    ]
