# Generated by Django 5.2 on 2026-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_chatmessage_viewing_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emote",
            name="code",
            field=models.CharField(
                help_text="Bare-word emote code, e.g. OMEGALUL (case-sensitive, no surrounding colons)",
                max_length=32,
                unique=True,
            ),
        ),
    ]
