# Generated by Django 5.2 on 2026-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_forumcategory_trackedchannel_announcement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamsettings",
            name="embed_id",
            field=models.CharField(
                blank=True,
                help_text="Rumble: the video/embed id (e.g. v6abcde from the video's Share -> Embed code). X: the post/tweet ID that contains the live video (the long number in the post URL).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="streamsettings",
            name="platform",
            field=models.CharField(
                choices=[
                    ("kick", "Kick"),
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                    ("rumble", "Rumble"),
                    ("x", "X (Twitter)"),
                ],
                default="kick",
                max_length=10,
            ),
        ),
    ]
