# Generated by Django 5.2 on 2026-06-22 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_streamsettings_embed_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable id used in access checks and OIDC claims",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="required_podcast",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only active subscribers to this podcast can view/post here. Blank = public.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_categories",
                to="home.podcast",
            ),
        ),
        migrations.AddField(
            model_name="streamsettings",
            name="required_podcast",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only active subscribers to this podcast can use this stream's live chat. Blank = open.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="streams",
                to="home.podcast",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token_hash"], name="home_emailv_token_h_9ed000_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no expiry", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="home.podcast",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="home_subscr_user_id_e66288_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "podcast"),
                        name="unique_user_podcast_subscription",
                    )
                ],
            },
        ),
    ]
