# Generated by Django 5.2 on 2026-06-23 01:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_podcast_forumcategory_required_podcast_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per month.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for a year (typically discounted vs. 12x monthly).",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="The tier/user class this purchase grants access to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="home.podcast",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Case-insensitive; stored uppercase.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "percent_off",
                    models.PositiveSmallIntegerField(
                        help_text="Percentage taken off the price (1-100). 100 = free.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "applies_to_all",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, the code works on every product.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for no start limit.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no expiry.", null=True
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave blank for unlimited.", null=True
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="When 'applies to all' is off, the products this code is valid for.",
                        related_name="coupons",
                        to="home.subscriptionproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Snapshot of product name at purchase.",
                        max_length=120,
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "coupon_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("discount_percent", models.PositiveSmallIntegerField(default=0)),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("granted_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="home.coupon",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="home.subscriptionproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="home_transa_user_id_c789a8_idx"
                    )
                ],
            },
        ),
    ]
