"""
Django settings for ibokki project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv()

SECRET_KEY = os.getenv('SECRET_KEY', 'fallback_key')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

KICK_CLIENT_ID = os.getenv("KICK_CLIENT_ID")

KICK_CLIENT_SECRET = os.getenv("KICK_CLIENT_SECRET")

ALLOWED_HOSTS = ["ibokki.com", "www.ibokki.com", "localhost", "127.0.0.1", ".ngrok-free.app"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "home.apps.HomeConfig",
    "csp",
]

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ibokki.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ibokki.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'home.auth.DiscordAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Custom user model
AUTH_USER_MODEL = 'home.CustomUser'

# Discord settings, loaded from .env
DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")

# Handle admin IDs
raw_admin_ids = os.getenv("DISCORD_ADMIN_IDS", "")
if DEBUG:
    print(f"\n=== Settings Debug ===")
    print(f"Raw DISCORD_ADMIN_IDS from env: {raw_admin_ids}")
    DISCORD_ADMIN_IDS = [id.strip().replace('discord_', '') for id in raw_admin_ids.split(",") if id.strip()]
    print(f"Processed DISCORD_ADMIN_IDS: {DISCORD_ADMIN_IDS}")
    print("=== End Settings Debug ===\n")

# Environment settings
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")  # 'local' or 'production'
BASE_URL = "http://localhost:8000" if ENVIRONMENT == "local" else os.getenv("BASE_URL", "https://your-production-domain.com")
# Ensure BASE_URL doesn't end with a slash
BASE_URL = BASE_URL.rstrip('/')
# Construct redirect URI with trailing slash to match URL pattern
DISCORD_REDIRECT_URI = f"{BASE_URL}/discord/callback/"

# Auth settings
LOGIN_URL = "/discord/login/"  # Use relative URL
LOGIN_REDIRECT_URL = "/watch/"  # Use relative URL

# Security settings
SECURE_SSL_REDIRECT = False
CSRF_COOKIE_SECURE = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

# Append slash settings
APPEND_SLASH = True
PREPEND_WWW = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# YouTube API Settings
YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY')

# Channels settings
ASGI_APPLICATION = "ibokki.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}


# Chat settings
CHAT_MESSAGE_MAX_LENGTH = 500
CHAT_MESSAGE_RATE_LIMIT = 1  # seconds between messages
CHAT_MESSAGE_HISTORY_LENGTH = 100  # number of messages to keep in history

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'home': {  # This will catch all loggers in the home app
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Content Security Policy settings
CSP_DEFAULT_SRC = ("'self'", "https:")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https:")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https:")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FRAME_SRC = (
    "'self'",
    "https://*.youtube.com",
    "https://*.twitch.tv",
    "https://*.kick.com",
    "https://kick.com",
    "https://player.kick.com",
    "https://*.rumble.com",
    "https://*.bitchute.com",
    "https://*.odysee.com",
    "https://*.vimeo.com",
    "https://*.dailymotion.com",
)
CSP_CONNECT_SRC = ("'self'", "https:", "wss:")
CSP_FONT_SRC = ("'self'", "https:", "data:")

# Enable CSP reporting in production
if not DEBUG:
    CSP_REPORT_ONLY = False
    CSP_REPORT_URI = '/csp-report/'
